export type BotPresetConfig = {
  contractType: string;
  desc: string;
  duration: number;
  durationUnit: "m" | "s" | "t";
  iconKey: "brain" | "cpu" | "flame" | "radar" | "shield" | "target" | "zap";
  id: string;
  market: string;
  martingale: number;
  maxRuns: number;
  name: string;
  predictionDigit: number;
  sl: number;
  stake: number;
  tp: number;
  tradeType: "even_odd" | "matches_differs" | "over_under" | "rise_fall";
};

export const BOT_PRESET_CONFIGS: BotPresetConfig[] = [
  {
    id: "under-destroyer-v2",
    name: "Underpro 3",
    iconKey: "target",
    desc: "Advanced Under strategy for precision digit trading.",
    market: "1HZ100V",
    tradeType: "over_under",
    contractType: "under",
    stake: 1.0,
    tp: 100.0,
    sl: 50.0,
    martingale: 2.0,
    duration: 1,
    durationUnit: "t",
    predictionDigit: 5,
    maxRuns: 50,
  },
  {
    id: "nova-v6",
    name: "Redsmaps Nova Stalker",
    iconKey: "cpu",
    desc: "Adaptive Under strategy tuned for fast 1-second index sessions with controlled recovery.",
    market: "1HZ100V",
    tradeType: "over_under",
    contractType: "under",
    stake: 1.0,
    tp: 100.0,
    sl: 10.0,
    martingale: 1.95,
    duration: 1,
    durationUnit: "t",
    predictionDigit: 5,
    maxRuns: 50,
  },
  {
    id: "mega-mind",
    name: "Redsmaps MegaMind Surge",
    iconKey: "brain",
    desc: "Digit Over scalper with measured recovery and fast tick execution on low-volatility indices.",
    market: "1HZ10V",
    tradeType: "over_under",
    contractType: "over",
    stake: 5.97,
    tp: 500.0,
    sl: 100.0,
    martingale: 2.0,
    duration: 1,
    durationUnit: "t",
    predictionDigit: 3,
    maxRuns: 50,
  },
  {
    id: "phantom-hit-run",
    name: "Redsmaps Phantom HitRun",
    iconKey: "flame",
    desc: "High-velocity Rise/Fall sniper built for short, decisive Volatility 100 bursts.",
    market: "R_100",
    tradeType: "rise_fall",
    contractType: "fall",
    stake: 1.0,
    tp: 10.0,
    sl: 5.0,
    martingale: 2.0,
    duration: 1,
    durationUnit: "t",
    predictionDigit: 5,
    maxRuns: 25,
  },
  {
    id: "candle-mine",
    name: "Redsmaps CandleVault Sentinel",
    iconKey: "zap",
    desc: "Digit Differs specialist targeting differs contracts with aggressive recovery controls.",
    market: "R_100",
    tradeType: "matches_differs",
    contractType: "differs",
    stake: 110.0,
    tp: 9999.0,
    sl: 9999.0,
    martingale: 11.0,
    duration: 1,
    durationUnit: "t",
    predictionDigit: 5,
    maxRuns: 25,
  },
  {
    id: "dec-entry",
    name: "Redsmaps Entry Point Sniper",
    iconKey: "target",
    desc: "Entry-point driven Digit Over setup built for traders who want precise trigger-based execution.",
    market: "1HZ10V",
    tradeType: "over_under",
    contractType: "over",
    stake: 1.0,
    tp: 2.0,
    sl: 2.0,
    martingale: 2.0,
    duration: 1,
    durationUnit: "t",
    predictionDigit: 7,
    maxRuns: 25,
  },
  {
    id: "auto-pilot-shield",
    name: "Redsmaps AutoPilot Shield",
    iconKey: "shield",
    desc: "Hands-off Digit Odd auto-bot designed for disciplined, hands-free volatility 100 sessions.",
    market: "R_100",
    tradeType: "even_odd",
    contractType: "odd",
    stake: 1.0,
    tp: 10.0,
    sl: 5.0,
    martingale: 2.0,
    duration: 1,
    durationUnit: "t",
    predictionDigit: 5,
    maxRuns: 25,
  },
  {
    id: "under-pro-bot",
    name: "Redsmaps UnderPro Vortex",
    iconKey: "radar",
    desc: "Under-focused setup tuned for Digit Under entries on Volatility 100 (1s).",
    market: "1HZ100V",
    tradeType: "over_under",
    contractType: "under",
    stake: 1.0,
    tp: 100.0,
    sl: 10.0,
    martingale: 1.95,
    duration: 1,
    durationUnit: "t",
    predictionDigit: 5,
    maxRuns: 50,
  },
];
