/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradingBotsRouteImport } from './routes/trading-bots'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as DerivCallbackRouteImport } from './routes/deriv-callback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopyTradingRouteImport } from './routes/copy-trading'
import { Route as Clone2006RouteImport } from './routes/clone2006'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as BotBuilderRouteImport } from './routes/bot-builder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as Clone2006IndexRouteImport } from './routes/clone2006.index'
import { Route as StrategySlugRouteImport } from './routes/strategy.$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as Clone2006TradingBotsRouteImport } from './routes/clone2006.trading-bots'
import { Route as Clone2006StrategiesRouteImport } from './routes/clone2006.strategies'
import { Route as Clone2006DashboardRouteImport } from './routes/clone2006.dashboard'
import { Route as Clone2006CopyTradingRouteImport } from './routes/clone2006.copy-trading'
import { Route as Clone2006ChartsRouteImport } from './routes/clone2006.charts'
import { Route as Clone2006BotBuilderRouteImport } from './routes/clone2006.bot-builder'
import { Route as Clone2006AuthRouteImport } from './routes/clone2006.auth'
import { Route as Clone2006AnalysisRouteImport } from './routes/clone2006.analysis'
import { Route as ApiDerivTokenExchangeRouteImport } from './routes/api/deriv-token-exchange'
import { Route as ApiDerivAccountsRouteImport } from './routes/api/deriv-accounts'
import { Route as ApiDerivAccountOtpRouteImport } from './routes/api/deriv-account-otp'
import { Route as ApiBotOrphanCheckRouteImport } from './routes/api/bot-orphan-check'
import { Route as ApiBotHandoffRouteImport } from './routes/api/bot-handoff'
import { Route as AdminProfitsRouteImport } from './routes/admin.profits'
import { Route as Clone2006DashboardIndexRouteImport } from './routes/clone2006.dashboard.index'
import { Route as Clone2006StrategySlugRouteImport } from './routes/clone2006.strategy.$slug'
import { Route as Clone2006DashboardSettingsRouteImport } from './routes/clone2006.dashboard.settings'
import { Route as Clone2006DashboardAnalyticsRouteImport } from './routes/clone2006.dashboard.analytics'

const TradingBotsRoute = TradingBotsRouteImport.update({
  id: '/trading-bots',
  path: '/trading-bots',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const DerivCallbackRoute = DerivCallbackRouteImport.update({
  id: '/deriv-callback',
  path: '/deriv-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyTradingRoute = CopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const Clone2006Route = Clone2006RouteImport.update({
  id: '/clone2006',
  path: '/clone2006',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const BotBuilderRoute = BotBuilderRouteImport.update({
  id: '/bot-builder',
  path: '/bot-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const Clone2006IndexRoute = Clone2006IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Clone2006Route,
} as any)
const StrategySlugRoute = StrategySlugRouteImport.update({
  id: '/strategy/$slug',
  path: '/strategy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const Clone2006TradingBotsRoute = Clone2006TradingBotsRouteImport.update({
  id: '/trading-bots',
  path: '/trading-bots',
  getParentRoute: () => Clone2006Route,
} as any)
const Clone2006StrategiesRoute = Clone2006StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => Clone2006Route,
} as any)
const Clone2006DashboardRoute = Clone2006DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Clone2006Route,
} as any)
const Clone2006CopyTradingRoute = Clone2006CopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => Clone2006Route,
} as any)
const Clone2006ChartsRoute = Clone2006ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => Clone2006Route,
} as any)
const Clone2006BotBuilderRoute = Clone2006BotBuilderRouteImport.update({
  id: '/bot-builder',
  path: '/bot-builder',
  getParentRoute: () => Clone2006Route,
} as any)
const Clone2006AuthRoute = Clone2006AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => Clone2006Route,
} as any)
const Clone2006AnalysisRoute = Clone2006AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => Clone2006Route,
} as any)
const ApiDerivTokenExchangeRoute = ApiDerivTokenExchangeRouteImport.update({
  id: '/api/deriv-token-exchange',
  path: '/api/deriv-token-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDerivAccountsRoute = ApiDerivAccountsRouteImport.update({
  id: '/api/deriv-accounts',
  path: '/api/deriv-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDerivAccountOtpRoute = ApiDerivAccountOtpRouteImport.update({
  id: '/api/deriv-account-otp',
  path: '/api/deriv-account-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotOrphanCheckRoute = ApiBotOrphanCheckRouteImport.update({
  id: '/api/bot-orphan-check',
  path: '/api/bot-orphan-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotHandoffRoute = ApiBotHandoffRouteImport.update({
  id: '/api/bot-handoff',
  path: '/api/bot-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfitsRoute = AdminProfitsRouteImport.update({
  id: '/admin/profits',
  path: '/admin/profits',
  getParentRoute: () => rootRouteImport,
} as any)
const Clone2006DashboardIndexRoute = Clone2006DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Clone2006DashboardRoute,
} as any)
const Clone2006StrategySlugRoute = Clone2006StrategySlugRouteImport.update({
  id: '/strategy/$slug',
  path: '/strategy/$slug',
  getParentRoute: () => Clone2006Route,
} as any)
const Clone2006DashboardSettingsRoute =
  Clone2006DashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Clone2006DashboardRoute,
  } as any)
const Clone2006DashboardAnalyticsRoute =
  Clone2006DashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => Clone2006DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/bot-builder': typeof BotBuilderRoute
  '/charts': typeof ChartsRoute
  '/clone2006': typeof Clone2006RouteWithChildren
  '/copy-trading': typeof CopyTradingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deriv-callback': typeof DerivCallbackRoute
  '/redirect': typeof RedirectRoute
  '/strategies': typeof StrategiesRoute
  '/trading-bots': typeof TradingBotsRoute
  '/admin/profits': typeof AdminProfitsRoute
  '/api/bot-handoff': typeof ApiBotHandoffRoute
  '/api/bot-orphan-check': typeof ApiBotOrphanCheckRoute
  '/api/deriv-account-otp': typeof ApiDerivAccountOtpRoute
  '/api/deriv-accounts': typeof ApiDerivAccountsRoute
  '/api/deriv-token-exchange': typeof ApiDerivTokenExchangeRoute
  '/clone2006/analysis': typeof Clone2006AnalysisRoute
  '/clone2006/auth': typeof Clone2006AuthRoute
  '/clone2006/bot-builder': typeof Clone2006BotBuilderRoute
  '/clone2006/charts': typeof Clone2006ChartsRoute
  '/clone2006/copy-trading': typeof Clone2006CopyTradingRoute
  '/clone2006/dashboard': typeof Clone2006DashboardRouteWithChildren
  '/clone2006/strategies': typeof Clone2006StrategiesRoute
  '/clone2006/trading-bots': typeof Clone2006TradingBotsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/strategy/$slug': typeof StrategySlugRoute
  '/clone2006/': typeof Clone2006IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/clone2006/dashboard/analytics': typeof Clone2006DashboardAnalyticsRoute
  '/clone2006/dashboard/settings': typeof Clone2006DashboardSettingsRoute
  '/clone2006/strategy/$slug': typeof Clone2006StrategySlugRoute
  '/clone2006/dashboard/': typeof Clone2006DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/bot-builder': typeof BotBuilderRoute
  '/charts': typeof ChartsRoute
  '/copy-trading': typeof CopyTradingRoute
  '/deriv-callback': typeof DerivCallbackRoute
  '/redirect': typeof RedirectRoute
  '/strategies': typeof StrategiesRoute
  '/trading-bots': typeof TradingBotsRoute
  '/admin/profits': typeof AdminProfitsRoute
  '/api/bot-handoff': typeof ApiBotHandoffRoute
  '/api/bot-orphan-check': typeof ApiBotOrphanCheckRoute
  '/api/deriv-account-otp': typeof ApiDerivAccountOtpRoute
  '/api/deriv-accounts': typeof ApiDerivAccountsRoute
  '/api/deriv-token-exchange': typeof ApiDerivTokenExchangeRoute
  '/clone2006/analysis': typeof Clone2006AnalysisRoute
  '/clone2006/auth': typeof Clone2006AuthRoute
  '/clone2006/bot-builder': typeof Clone2006BotBuilderRoute
  '/clone2006/charts': typeof Clone2006ChartsRoute
  '/clone2006/copy-trading': typeof Clone2006CopyTradingRoute
  '/clone2006/strategies': typeof Clone2006StrategiesRoute
  '/clone2006/trading-bots': typeof Clone2006TradingBotsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/strategy/$slug': typeof StrategySlugRoute
  '/clone2006': typeof Clone2006IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/clone2006/dashboard/analytics': typeof Clone2006DashboardAnalyticsRoute
  '/clone2006/dashboard/settings': typeof Clone2006DashboardSettingsRoute
  '/clone2006/strategy/$slug': typeof Clone2006StrategySlugRoute
  '/clone2006/dashboard': typeof Clone2006DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/bot-builder': typeof BotBuilderRoute
  '/charts': typeof ChartsRoute
  '/clone2006': typeof Clone2006RouteWithChildren
  '/copy-trading': typeof CopyTradingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deriv-callback': typeof DerivCallbackRoute
  '/redirect': typeof RedirectRoute
  '/strategies': typeof StrategiesRoute
  '/trading-bots': typeof TradingBotsRoute
  '/admin/profits': typeof AdminProfitsRoute
  '/api/bot-handoff': typeof ApiBotHandoffRoute
  '/api/bot-orphan-check': typeof ApiBotOrphanCheckRoute
  '/api/deriv-account-otp': typeof ApiDerivAccountOtpRoute
  '/api/deriv-accounts': typeof ApiDerivAccountsRoute
  '/api/deriv-token-exchange': typeof ApiDerivTokenExchangeRoute
  '/clone2006/analysis': typeof Clone2006AnalysisRoute
  '/clone2006/auth': typeof Clone2006AuthRoute
  '/clone2006/bot-builder': typeof Clone2006BotBuilderRoute
  '/clone2006/charts': typeof Clone2006ChartsRoute
  '/clone2006/copy-trading': typeof Clone2006CopyTradingRoute
  '/clone2006/dashboard': typeof Clone2006DashboardRouteWithChildren
  '/clone2006/strategies': typeof Clone2006StrategiesRoute
  '/clone2006/trading-bots': typeof Clone2006TradingBotsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/strategy/$slug': typeof StrategySlugRoute
  '/clone2006/': typeof Clone2006IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/clone2006/dashboard/analytics': typeof Clone2006DashboardAnalyticsRoute
  '/clone2006/dashboard/settings': typeof Clone2006DashboardSettingsRoute
  '/clone2006/strategy/$slug': typeof Clone2006StrategySlugRoute
  '/clone2006/dashboard/': typeof Clone2006DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/auth'
    | '/bot-builder'
    | '/charts'
    | '/clone2006'
    | '/copy-trading'
    | '/dashboard'
    | '/deriv-callback'
    | '/redirect'
    | '/strategies'
    | '/trading-bots'
    | '/admin/profits'
    | '/api/bot-handoff'
    | '/api/bot-orphan-check'
    | '/api/deriv-account-otp'
    | '/api/deriv-accounts'
    | '/api/deriv-token-exchange'
    | '/clone2006/analysis'
    | '/clone2006/auth'
    | '/clone2006/bot-builder'
    | '/clone2006/charts'
    | '/clone2006/copy-trading'
    | '/clone2006/dashboard'
    | '/clone2006/strategies'
    | '/clone2006/trading-bots'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/strategy/$slug'
    | '/clone2006/'
    | '/dashboard/'
    | '/clone2006/dashboard/analytics'
    | '/clone2006/dashboard/settings'
    | '/clone2006/strategy/$slug'
    | '/clone2006/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/auth'
    | '/bot-builder'
    | '/charts'
    | '/copy-trading'
    | '/deriv-callback'
    | '/redirect'
    | '/strategies'
    | '/trading-bots'
    | '/admin/profits'
    | '/api/bot-handoff'
    | '/api/bot-orphan-check'
    | '/api/deriv-account-otp'
    | '/api/deriv-accounts'
    | '/api/deriv-token-exchange'
    | '/clone2006/analysis'
    | '/clone2006/auth'
    | '/clone2006/bot-builder'
    | '/clone2006/charts'
    | '/clone2006/copy-trading'
    | '/clone2006/strategies'
    | '/clone2006/trading-bots'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/strategy/$slug'
    | '/clone2006'
    | '/dashboard'
    | '/clone2006/dashboard/analytics'
    | '/clone2006/dashboard/settings'
    | '/clone2006/strategy/$slug'
    | '/clone2006/dashboard'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/auth'
    | '/bot-builder'
    | '/charts'
    | '/clone2006'
    | '/copy-trading'
    | '/dashboard'
    | '/deriv-callback'
    | '/redirect'
    | '/strategies'
    | '/trading-bots'
    | '/admin/profits'
    | '/api/bot-handoff'
    | '/api/bot-orphan-check'
    | '/api/deriv-account-otp'
    | '/api/deriv-accounts'
    | '/api/deriv-token-exchange'
    | '/clone2006/analysis'
    | '/clone2006/auth'
    | '/clone2006/bot-builder'
    | '/clone2006/charts'
    | '/clone2006/copy-trading'
    | '/clone2006/dashboard'
    | '/clone2006/strategies'
    | '/clone2006/trading-bots'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/strategy/$slug'
    | '/clone2006/'
    | '/dashboard/'
    | '/clone2006/dashboard/analytics'
    | '/clone2006/dashboard/settings'
    | '/clone2006/strategy/$slug'
    | '/clone2006/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AuthRoute: typeof AuthRoute
  BotBuilderRoute: typeof BotBuilderRoute
  ChartsRoute: typeof ChartsRoute
  Clone2006Route: typeof Clone2006RouteWithChildren
  CopyTradingRoute: typeof CopyTradingRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DerivCallbackRoute: typeof DerivCallbackRoute
  RedirectRoute: typeof RedirectRoute
  StrategiesRoute: typeof StrategiesRoute
  TradingBotsRoute: typeof TradingBotsRoute
  AdminProfitsRoute: typeof AdminProfitsRoute
  ApiBotHandoffRoute: typeof ApiBotHandoffRoute
  ApiBotOrphanCheckRoute: typeof ApiBotOrphanCheckRoute
  ApiDerivAccountOtpRoute: typeof ApiDerivAccountOtpRoute
  ApiDerivAccountsRoute: typeof ApiDerivAccountsRoute
  ApiDerivTokenExchangeRoute: typeof ApiDerivTokenExchangeRoute
  StrategySlugRoute: typeof StrategySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading-bots': {
      id: '/trading-bots'
      path: '/trading-bots'
      fullPath: '/trading-bots'
      preLoaderRoute: typeof TradingBotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deriv-callback': {
      id: '/deriv-callback'
      path: '/deriv-callback'
      fullPath: '/deriv-callback'
      preLoaderRoute: typeof DerivCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-trading': {
      id: '/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof CopyTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clone2006': {
      id: '/clone2006'
      path: '/clone2006'
      fullPath: '/clone2006'
      preLoaderRoute: typeof Clone2006RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-builder': {
      id: '/bot-builder'
      path: '/bot-builder'
      fullPath: '/bot-builder'
      preLoaderRoute: typeof BotBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/clone2006/': {
      id: '/clone2006/'
      path: '/'
      fullPath: '/clone2006/'
      preLoaderRoute: typeof Clone2006IndexRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/strategy/$slug': {
      id: '/strategy/$slug'
      path: '/strategy/$slug'
      fullPath: '/strategy/$slug'
      preLoaderRoute: typeof StrategySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/clone2006/trading-bots': {
      id: '/clone2006/trading-bots'
      path: '/trading-bots'
      fullPath: '/clone2006/trading-bots'
      preLoaderRoute: typeof Clone2006TradingBotsRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/clone2006/strategies': {
      id: '/clone2006/strategies'
      path: '/strategies'
      fullPath: '/clone2006/strategies'
      preLoaderRoute: typeof Clone2006StrategiesRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/clone2006/dashboard': {
      id: '/clone2006/dashboard'
      path: '/dashboard'
      fullPath: '/clone2006/dashboard'
      preLoaderRoute: typeof Clone2006DashboardRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/clone2006/copy-trading': {
      id: '/clone2006/copy-trading'
      path: '/copy-trading'
      fullPath: '/clone2006/copy-trading'
      preLoaderRoute: typeof Clone2006CopyTradingRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/clone2006/charts': {
      id: '/clone2006/charts'
      path: '/charts'
      fullPath: '/clone2006/charts'
      preLoaderRoute: typeof Clone2006ChartsRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/clone2006/bot-builder': {
      id: '/clone2006/bot-builder'
      path: '/bot-builder'
      fullPath: '/clone2006/bot-builder'
      preLoaderRoute: typeof Clone2006BotBuilderRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/clone2006/auth': {
      id: '/clone2006/auth'
      path: '/auth'
      fullPath: '/clone2006/auth'
      preLoaderRoute: typeof Clone2006AuthRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/clone2006/analysis': {
      id: '/clone2006/analysis'
      path: '/analysis'
      fullPath: '/clone2006/analysis'
      preLoaderRoute: typeof Clone2006AnalysisRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/api/deriv-token-exchange': {
      id: '/api/deriv-token-exchange'
      path: '/api/deriv-token-exchange'
      fullPath: '/api/deriv-token-exchange'
      preLoaderRoute: typeof ApiDerivTokenExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deriv-accounts': {
      id: '/api/deriv-accounts'
      path: '/api/deriv-accounts'
      fullPath: '/api/deriv-accounts'
      preLoaderRoute: typeof ApiDerivAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deriv-account-otp': {
      id: '/api/deriv-account-otp'
      path: '/api/deriv-account-otp'
      fullPath: '/api/deriv-account-otp'
      preLoaderRoute: typeof ApiDerivAccountOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-orphan-check': {
      id: '/api/bot-orphan-check'
      path: '/api/bot-orphan-check'
      fullPath: '/api/bot-orphan-check'
      preLoaderRoute: typeof ApiBotOrphanCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-handoff': {
      id: '/api/bot-handoff'
      path: '/api/bot-handoff'
      fullPath: '/api/bot-handoff'
      preLoaderRoute: typeof ApiBotHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profits': {
      id: '/admin/profits'
      path: '/admin/profits'
      fullPath: '/admin/profits'
      preLoaderRoute: typeof AdminProfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clone2006/dashboard/': {
      id: '/clone2006/dashboard/'
      path: '/'
      fullPath: '/clone2006/dashboard/'
      preLoaderRoute: typeof Clone2006DashboardIndexRouteImport
      parentRoute: typeof Clone2006DashboardRoute
    }
    '/clone2006/strategy/$slug': {
      id: '/clone2006/strategy/$slug'
      path: '/strategy/$slug'
      fullPath: '/clone2006/strategy/$slug'
      preLoaderRoute: typeof Clone2006StrategySlugRouteImport
      parentRoute: typeof Clone2006Route
    }
    '/clone2006/dashboard/settings': {
      id: '/clone2006/dashboard/settings'
      path: '/settings'
      fullPath: '/clone2006/dashboard/settings'
      preLoaderRoute: typeof Clone2006DashboardSettingsRouteImport
      parentRoute: typeof Clone2006DashboardRoute
    }
    '/clone2006/dashboard/analytics': {
      id: '/clone2006/dashboard/analytics'
      path: '/analytics'
      fullPath: '/clone2006/dashboard/analytics'
      preLoaderRoute: typeof Clone2006DashboardAnalyticsRouteImport
      parentRoute: typeof Clone2006DashboardRoute
    }
  }
}

interface Clone2006DashboardRouteChildren {
  Clone2006DashboardAnalyticsRoute: typeof Clone2006DashboardAnalyticsRoute
  Clone2006DashboardSettingsRoute: typeof Clone2006DashboardSettingsRoute
  Clone2006DashboardIndexRoute: typeof Clone2006DashboardIndexRoute
}

const Clone2006DashboardRouteChildren: Clone2006DashboardRouteChildren = {
  Clone2006DashboardAnalyticsRoute: Clone2006DashboardAnalyticsRoute,
  Clone2006DashboardSettingsRoute: Clone2006DashboardSettingsRoute,
  Clone2006DashboardIndexRoute: Clone2006DashboardIndexRoute,
}

const Clone2006DashboardRouteWithChildren =
  Clone2006DashboardRoute._addFileChildren(Clone2006DashboardRouteChildren)

interface Clone2006RouteChildren {
  Clone2006AnalysisRoute: typeof Clone2006AnalysisRoute
  Clone2006AuthRoute: typeof Clone2006AuthRoute
  Clone2006BotBuilderRoute: typeof Clone2006BotBuilderRoute
  Clone2006ChartsRoute: typeof Clone2006ChartsRoute
  Clone2006CopyTradingRoute: typeof Clone2006CopyTradingRoute
  Clone2006DashboardRoute: typeof Clone2006DashboardRouteWithChildren
  Clone2006StrategiesRoute: typeof Clone2006StrategiesRoute
  Clone2006TradingBotsRoute: typeof Clone2006TradingBotsRoute
  Clone2006IndexRoute: typeof Clone2006IndexRoute
  Clone2006StrategySlugRoute: typeof Clone2006StrategySlugRoute
}

const Clone2006RouteChildren: Clone2006RouteChildren = {
  Clone2006AnalysisRoute: Clone2006AnalysisRoute,
  Clone2006AuthRoute: Clone2006AuthRoute,
  Clone2006BotBuilderRoute: Clone2006BotBuilderRoute,
  Clone2006ChartsRoute: Clone2006ChartsRoute,
  Clone2006CopyTradingRoute: Clone2006CopyTradingRoute,
  Clone2006DashboardRoute: Clone2006DashboardRouteWithChildren,
  Clone2006StrategiesRoute: Clone2006StrategiesRoute,
  Clone2006TradingBotsRoute: Clone2006TradingBotsRoute,
  Clone2006IndexRoute: Clone2006IndexRoute,
  Clone2006StrategySlugRoute: Clone2006StrategySlugRoute,
}

const Clone2006RouteWithChildren = Clone2006Route._addFileChildren(
  Clone2006RouteChildren,
)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AuthRoute: AuthRoute,
  BotBuilderRoute: BotBuilderRoute,
  ChartsRoute: ChartsRoute,
  Clone2006Route: Clone2006RouteWithChildren,
  CopyTradingRoute: CopyTradingRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DerivCallbackRoute: DerivCallbackRoute,
  RedirectRoute: RedirectRoute,
  StrategiesRoute: StrategiesRoute,
  TradingBotsRoute: TradingBotsRoute,
  AdminProfitsRoute: AdminProfitsRoute,
  ApiBotHandoffRoute: ApiBotHandoffRoute,
  ApiBotOrphanCheckRoute: ApiBotOrphanCheckRoute,
  ApiDerivAccountOtpRoute: ApiDerivAccountOtpRoute,
  ApiDerivAccountsRoute: ApiDerivAccountsRoute,
  ApiDerivTokenExchangeRoute: ApiDerivTokenExchangeRoute,
  StrategySlugRoute: StrategySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
